services:
  api:
    container_name: api
    restart: always
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
    depends_on:
      - db
    networks:
      - chicken_network
  db:
    container_name: db
    restart: always
    image: postgres:15
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - chicken_network

networks:
  chicken_network:
    name: chicken_network
    external: false
